-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgAQDY+46vfF0VDyRr
+YZ3BRL8IIXo4upmAoo2dCmgZ/ygCgYIKoZIzj0DAQehRANCAAR6YQYxHxae+kjs
PbHRQKHMZ/a6XkSb5mSvnbyhj5sq8rJ+ccoshxpBat3yCs653qp6XgdhVw5LSIH1
PMKV0ZFz
-----END PRIVATE KEY-----