FROM php:8.2-cli AS base

# Install system dependencies
RUN apt-get update && apt-get install -y \
    supervisor \
    zip \
    unzip \
    git \
    curl \
    ffmpeg \
    vim \
    libavcodec-extra \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev  \
    pkg-config \
    libicu-dev \
    libzip-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libssl-dev

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN  pecl channel-update pecl.php.net \
    && printf "no\nno\nno\nno\nno\nno\nno\nno\nno\nno\nno\nno\n" | pecl install swoole \
    && docker-php-ext-enable swoole \
    && docker-php-ext-install pdo_mysql  mbstring exif pcntl bcmath gd zip opcache intl

RUN rm /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini

COPY docker/docker-php-ext-opcache.ini /usr/local/etc/php/conf.d/
COPY docker/docker-php-uploads.ini /usr/local/etc/php/conf.d/
COPY docker/99-myapp-pm.ini /usr/local/etc/php/conf.d/


# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /app

# Copy application files
COPY . /app

# Recreate storage dirs excluded by .dockerignore
RUN mkdir -p storage/framework/cache storage/framework/data storage/framework/sessions storage/framework/testing storage/framework/views storage/logs bootstrap/cache

# Setup supervisord configuration
COPY docker/octana-supervisor.conf /etc/supervisor/conf.d/supervisord.conf



RUN env REDIS_HOST=172.17.0.1 \
    composer install --no-dev --no-interaction --ignore-platform-reqs   --optimize-autoloader --no-scripts
 

ENV OCTANE_WORKERS=4
ENV OCTANE_MAX_REQUESTS=500
ENV OCTANE_TASK_WORKERS=4
ENV OCTANE_SERVER="swoole"



COPY docker/octane.php /app/config/octane.php
#COPY docker/auth.php   /app/config/auth.php

RUN chmod -R 777 /app/storage
RUN chmod -R 777 /app/bootstrap
RUN chmod 777 /app/public/settings.json

## migrations - will run after deployment
#RUN REDIS_HOST=172.17.0.1 \
 #   php artisan migrate --force
#RUN REDIS_HOST=172.17.0.1 \
 #   php artisan optimize:clear

#COPY docker/nginx-octana.conf /etc/nginx/sites-available/default
#EXPOSE 80


# Expose port 9000
EXPOSE 8000

# Start supervisord
CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

