FROM php:8.2-cli

# Install system dependencies
RUN apt update && apt install -y \
    cron \
    supervisor \
    zip \
    unzip \
    git \
    curl \
    vim \
    libavcodec-extra \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libicu-dev \
    libzip-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libwebp-dev \
    ffmpeg \
    && apt clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip opcache intl

COPY docker/99-appjob-mem.ini /usr/local/etc/php/conf.d/

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /app

# Copy composer files first for layer caching
COPY composer.json composer.lock /app/

# Install dependencies (cached unless composer.json/lock change)
RUN env REDIS_HOST=172.17.0.1 \
	 composer install --no-dev --optimize-autoloader

# Now copy the rest of the application
COPY . /app

# Copy the crontab file
COPY docker/cron /etc/cron.d/app-cron

# Give execution rights to the cron job
RUN chmod 0644 /etc/cron.d/app-cron

# Create log file for cron
RUN touch /var/log/cron.log

RUN crontab -u root /etc/cron.d/app-cron

# Setup supervisord configuration
COPY docker/jobs-supervisor.conf /etc/supervisor/conf.d/supervisord.conf

RUN chmod -R 777 /app/storage /app/bootstrap \
    && chmod 777 /app/public/settings.json

RUN REDIS_HOST=172.17.0.1 \
    php artisan optimize:clear

# Start supervisord
CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
