version: '3.8'

services:
  rixo-chat-octa:
    image: ${OCTA_IMAGE}
    ports:
      - "8080:8000"
    volumes:
      - /var/www/rixo-chat/.env:/app/.env
      - /var/www/rixo-chat/gcp.json:/app/docker/gcp.json
      - /var/www/rixo-chat/public/settings.json:/app/public/settings.json
      - /var/www/rixo-chat/storage:/app/storage
    networks:
      - app-network
    deploy:
      replicas: 4
      update_config:
        order: start-first
        failure_action: rollback
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1200M

  rixo-chat-job:
    image: ${JOB_IMAGE}
    volumes:
      - /var/www/rixo-chat/.env:/app/.env
      - /var/www/rixo-chat/gcp.json:/app/docker/gcp.json
      - /var/www/rixo-chat/storage:/app/storage
    networks:
      - app-network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1500M

  rixo-chat-cron:
    image: ${JOB_IMAGE}
    init: true
    command: ["php", "/app/artisan", "schedule:work"]
    volumes:
      - /var/www/rixo-chat/.env:/app/.env
      - /var/www/rixo-chat/gcp.json:/app/docker/gcp.json
      - /var/www/rixo-chat/storage:/app/storage
    networks:
      - app-network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  rixo-chat-zigo-worker:
    image: ${JOB_IMAGE}
    command: ["php", "/app/artisan", "app:handling-room-zigo-requests"]
    volumes:
      - /var/www/rixo-chat/.env:/app/.env
      - /var/www/rixo-chat/gcp.json:/app/docker/gcp.json
      - /var/www/rixo-chat/storage:/app/storage
    networks:
      - app-network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis:
    image: redis:latest
    command: ["redis-server", "--timeout", "0", "--tcp-keepalive", "60", "--maxmemory", "1gb", "--maxmemory-policy", "allkeys-lru"]
    ports:
      - "6379:6379"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 1G

  node-google-pay:
    image: node-google-pay:2
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: q7s5ppqh7msig6kannz2d74m8
