[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:critical-worker]
process_name=%(program_name)s
command=php /app/artisan queue:work --queue=default,notification,notification_heavy,wallet,increment-diamond --max-jobs=1000
directory=/app
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/app/storage/jobs-logs/critical-worker.log

[program:heavy-worker]
process_name=%(program_name)s
command=php /app/artisan queue:work --queue=heavy1,heavy2,heavy3,pk-job,updatePk,updatePkAndSendToZigo,charisma-job,achievement,level_rewards --max-jobs=1000
directory=/app
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/app/storage/jobs-logs/heavy-worker.log

[program:background-worker]
process_name=%(program_name)s
command=php /app/artisan queue:work --queue=luckyBox,lucky_gift,lucky_gift_2,lucky_gift_3,sendComment,log_user_coin,test-super-lucky-box,official-message,follow_counts,milestones-job --max-jobs=1000
directory=/app
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/app/storage/jobs-logs/background-worker.log

[program:gifts-worker]
process_name=%(program_name)s
command=php /app/artisan queue:work --queue=gifts --timeout=300 --tries=3 --max-jobs=1000
directory=/app
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/app/storage/jobs-logs/gifts.log

[program:zigo-handler]
process_name=%(program_name)s
command=php /app/artisan app:handling-room-zigo-requests
directory=/app
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/app/storage/jobs-logs/zigo.log
