[program:achievement]
command=php /app/artisan queue:work --queue=achievement --rest=3 --sleep=3
numprocs=1
autostart=true
autorestart=true

[program:pk-wallet]
command=php /app/artisan queue:work --queue=pk-job,wallet,increment-diamond,updatePk,updatePkAndSendToZigo --rest=1 --sleep=3
numprocs=1
autostart=true
autorestart=true

[program:heavy-tasks]
command=php /app/artisan queue:work --queue=heavy1,heavy2,heavy3 --rest=10 --sleep=5
numprocs=1
autostart=true
autorestart=true

[program:notifications]
command=php /app/artisan queue:work --queue=notification,notification_heavy,official-message --rest=15 --sleep=5
numprocs=1
autostart=true
autorestart=true

[program:lucky-box]
command=php /app/artisan queue:work --queue=luckyBox,lucky_gift,lucky_gift_2,lucky_gift_3,test-super-lucky-box --rest=5 --sleep=3
numprocs=1
autostart=true
autorestart=true

[program:default-workers]
command=php /app/artisan queue:work --queue=default,sendComment,log_user_coin,follow_counts,level_rewards,charisma-job --rest=5 --sleep=3
numprocs=1
autostart=true
autorestart=true

[program:catch-all]
command=php /app/artisan queue:work --rest=10 --sleep=5
numprocs=1
autostart=true
autorestart=true
