<?php

namespace App\Admin\Controllers;

use App\Models\Admin;
use App\Models\Agency;
use App\Models\Agent;
use App\Models\User;
use Encore\Admin\Auth\Permission;
use Encore\Admin\Layout\Content;
use Illuminate\Support\Facades\DB;
use function Doctrine\Common\Cache\Psr6\get;

class AdminUserController extends EncorUsersController
{
// \Encore\Admin\Controllers\UserController

    protected $model;

    public $permission_name = 'auth-users';

    public function __construct ()
    {
        $userModel = Admin::class;
        $this->model = new $userModel;
    }

    public function edit ( $id , Content $content )
    {
       // Permission::check('developer');

       if (!Admin::user()->can('*')) {
        Permission::check('edit-' . $this->permission_name);
    }


        return parent ::edit ( $id , $content ); // TODO: Change the autogenerated stub
    }

    public function update ( $id )
    {

        if (!Admin::user()->can('*')) {
            Permission::check('update-' . $this->permission_name);
        }
        $user = Admin::query ()->findOrFail ($id);
        if (\request ('password') != $user->password || \request ('username') != $user->username){
            Agent::where("id",$user->id)->update([
                "remember_token" => null
            ]);
            DB::table ('sessions')->where ('user_id',$user->id)->delete ();
        }
        return parent ::update ($id);
    }

    public function destroy ( $id )
    {
        if (!Admin::user()->can('*')) {
            Permission::check('delete-' . $this->permission_name);
        }

        $user = $this->model->find($id);
        if ($user){
            if ($user->isRole('admin') || $user->isRole('developer')){
                return response ()->json (['error'=>'','message'=>__('admin cant be deleted')]);
            }
        }
        Agency::query ()->where ('owner_id',$id)->delete ();
        return parent ::destroy ($id);

    }

    public function form ()
    {

        $form =  parent ::form (); // TODO: Change the autogenerated stub
        $form->select('app_id', __('validation.select_user'))
        ->options(User::pluck('name', 'id')) // Fetch users' names and IDs
        ->rules('required'); // Allow it to be optional


        return $form;
    }


}
