<?php

namespace App\Admin\Controllers;

use Admin as GlobalAdmin;
use App\Models\Admin as ModelsAdmin;
use App\Models\Agent;
use Encore\Admin\Form;
use Illuminate\Http\Request;
use Encore\Admin\Facades\Admin;
use Encore\Admin\Layout\Content;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\MessageBag;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Cookie;
use KevinSoft\MultiLanguage\MultiLanguage;
use Jenssegers\Agent\Agent as JenssegersAgent;
use Stevebauman\Location\Facades\Location;
use App\Models\AdminLoginLog;
use Encore\Admin\Controllers\AuthController as BaseAuthController;

class AuthController extends BaseAuthController
{

    public function createPreviewUser(Request $request)
    {

        \App\Models\Admin::where('is_preview', true)->delete();

        $roleId = $request->role_id;
        $password = \Str::random(12);
        $values = [
            'username' => \Str::random(9),
            'password' => $password,
        ];
        $admin = \App\Models\Admin::create([
            ...$values,
            'name' => \Str::random(9),
            'is_preview' => true,
            'password' => bcrypt($password)
        ]);

        $admin->roles()->sync(['role_id' => $roleId]);
        //        Config::set('session.cookie', 'laravel_preview');
        //        Config::set('session.domain', 'https://top_star_backend.test');

        $token = '';



        return response()->json(['url' => '/preview/admin/login?token=' . $admin->id]);
    }

    public function putSetting()
    {
        if (\request('password') != Admin::user()->getAuthPassword()) {
            Agent::where("id", Admin::user()->id)->update([
                "remember_token" => null
            ]);
            DB::table('sessions')->where('user_id', Admin::user()->getAuthIdentifier())->delete();
        }
        return parent::putSetting(); // TODO: Change the autogenerated stub
    }

    public function getLogin()
    {
        $languages = MultiLanguage::config("languages");
        $cookie_name = MultiLanguage::config('cookie-name', 'locale');

        $current = MultiLanguage::config('default');
        if (Cookie::has($cookie_name)) {
            $current = Cookie::get($cookie_name);
        }
        return view("multi-language::login", compact('languages', 'current'));
    }

    // public function postLogin(Request $request)
    // {

    //     $url = $request->url;

    //     $this->loginValidator($request->all())->validate();
    //     $admin = DB::table('admin_users')
    //         ->where('username', request('username'))
    //         ->where('type', null)
    //         ->exists();
    //     if ($admin) {
    //         $credentials = $request->only([$this->username(), 'password']);
    //         $remember = $request->get('remember', false);

    //         if ($this->guard()->attempt($credentials, $remember)) {
    //             return $this->sendLoginResponse($request);
    //         }
    //     }


    //     return back()->withInput()->withErrors([
    //         $this->username() => $this->getFailedLoginMessage(),
    //     ]);
    // }

    // public function sendLoginResponse(Request $request)
    // {
    //     admin_toastr(trans('admin.login_successful'));

    //     $request->session()->regenerate();
    //     if (Auth::user()->roles->contains('slug', 'bd')) {
    //         return redirect()->route('bd.home');
    //     }
    //    // dd(Auth::user());

    //     return redirect()->intended($request->url ?? $this->redirectPath());
    // }



    public function postLogin(Request $request)
    {
        $this->loginValidator($request->all())->validate();

        $admin = DB::table('admin_users')
            ->where('username', $request->username)
            ->whereNull('type')
            ->first();

        if (!$admin) {
            return back()->withInput()->withErrors([
                $this->username() => trans('admin.username_not_found'),
            ]);
        }

        if (!Hash::check($request->password, $admin->password)) {
            return back()->withInput()->withErrors([
                'password' => trans('admin.password_incorrect'),
            ]);
        }

        Auth::guard('admin')->loginUsingId($admin->id, $request->boolean('remember'));

        $sessionToken = \Str::random(40);
        DB::table('admin_users')->where('id', $admin->id)->update(['session_token' => $sessionToken]);
        $request->session()->put('admin_session_token', $sessionToken);

        // Mark previous login logs as logged out (use PHP now() for both to avoid timezone mismatch)
        $now = now();
        $previousLogs = AdminLoginLog::where('user_id', $admin->id)
            ->whereNull('logout_at')
            ->whereNotNull('login_at')
            ->get();
        foreach ($previousLogs as $prevLog) {
            $prevLog->update([
                'logout_at' => $now,
                'session_duration_minutes' => (int) $now->diffInMinutes($prevLog->login_at),
            ]);
        }

        try {
            $agent = new JenssegersAgent();
            $ip = $request->ip();
            $location = Location::get($ip);

            $loginLog = AdminLoginLog::create([
                'user_id'          => $admin->id,
                'path'             => 'admin/login',
                'method'           => 'POST',
                'ip'               => $ip,
                'input'            => json_encode($request->except(['password', '_token'])),
                'country'          => $location->countryName ?? null,
                'city'             => $location->cityName ?? null,
                'region'           => $location->regionName ?? null,
                'latitude'         => $location->latitude ?? null,
                'longitude'        => $location->longitude ?? null,
                'device'           => $agent->device() ?: ($agent->isDesktop() ? 'Desktop' : ($agent->isMobile() ? 'Mobile' : ($agent->isTablet() ? 'Tablet' : 'Unknown'))),
                'platform'         => $agent->platform(),
                'platform_version' => $agent->version($agent->platform()),
                'browser'          => $agent->browser(),
                'browser_version'  => $agent->version($agent->browser()),
                'user_agent'       => $request->userAgent(),
                'login_at'         => now(),
            ]);

            $request->session()->put('admin_login_log_id', $loginLog->id);
        } catch (\Exception $e) {
            \Log::warning('Failed to save admin login log: ' . $e->getMessage());
        }

        return $this->sendLoginResponse($request);
    }

    public function sendLoginResponse(Request $request)
    {
        admin_toastr(trans('admin.login_successful'));

        $request->session()->regenerate();

        $user = Auth::guard('admin')->user();

        // Role-based redirect
        if ($user->roles->contains('slug', 'bd')) {
            return redirect()->route('bd.home');
        }

        $url = $this->getFirstUrl($user);
      //  dd($url, $request->url);
        $redirectUrl = $request->url != "/admin" ? $request->url : $url;
        return redirect()->intended(
            $redirectUrl
            /**$this->redirectPath()*/
        );
    }



    public function getFirstUrl($user)
    {
        $permissionSlugs = $user->roles
            ->flatMap->permissions
            ->unique('id')
            ->pluck('slug');

        if ($permissionSlugs->isEmpty()) {
            return admin_url(); // fallback
        }

        $firstPermission = DB::table('admin_permissions')
            ->join('role_categories', 'admin_permissions.category', '=', 'role_categories.slug')
            ->whereIn('admin_permissions.slug', $permissionSlugs)
            ->where('admin_permissions.slug', 'like', 'browse-%')
            ->orderBy('role_categories.sort', 'asc')
            ->orderBy('admin_permissions.id', 'asc')
            ->select('admin_permissions.slug')
            ->first();


        // Fallback if no permission found
        $permissionSlug = $firstPermission->slug ?? 'browse-dashboard';

        $menuUrl = DB::table('admin_menu')
            ->where('permission', $permissionSlug)
            ->whereNotNull('uri')
            ->where('uri', '!=', '')
            ->value('uri');

        return $menuUrl ? admin_url($menuUrl) : admin_url();
    }

    public function getSetting(Content $content)
    {
        $form = $this->settingForm();
        $form->tools(
            function (Form\Tools $tools) {
                $tools->disableList();
                $tools->disableDelete();
                $tools->disableView();
            }
        );

        return $content
            ->title(trans('admin.user_setting'))
            ->body($form->edit(Admin::user()->id));
    }

    protected function settingForm()
    {

        $class = config('admin.database.users_model');

        $form = new Form(new $class());

        $form->display('username', trans('admin.username'));
        $form->text('name', trans('admin.name'))->rules('required');
        $form->image('avatar', trans('admin.avatar'));
        if (!(Auth::user()->username == 'demo')) {
            $form->password('password', trans('admin.password'))->rules('confirmed|required');
            $form->password('password_confirmation', trans('admin.password_confirmation'))->rules('required')
                ->default(function ($form) {
                    return $form->model()->password;
                });
        }

        $form->setAction(admin_url('auth/setting'));

        $form->ignore(['password_confirmation']);

        $form->saving(function (Form $form) {
            if ($form->model()->password != $form->password && $form->model()->username == 'admin' || $form->model()->password_confirmation != $form->password_confirmation && $form->model()->username == 'admin') {
                $error = new MessageBag(
                    [
                        'title'   => 'forbidden',
                        'message' => 'you can not make change',
                    ]
                );
                return back()->with(compact('error'));
            }
            if ($form->password && $form->model()->password != $form->password) {
                $form->password = Hash::make($form->password);
            }
        });

        $form->saved(function () {
            admin_toastr(trans('admin.update_succeeded'));

            return redirect(admin_url('auth/setting'));
        });

        return $form;
    }

    public function getLogout(Request $request)
    {
        $this->updateLoginLogSessionDuration($request);

        $this->guard()->logout();

        $request->session()->invalidate();

        return redirect(config('admin.route.prefix'));
    }

    private function updateLoginLogSessionDuration(Request $request): void
    {
        try {
            $loginLogId = $request->session()->get('admin_login_log_id');
            if ($loginLogId) {
                $log = AdminLoginLog::find($loginLogId);
                if ($log) {
                    $log->update([
                        'logout_at' => now(),
                        'session_duration_minutes' => (int) now()->diffInMinutes($log->login_at),
                    ]);
                }
            }
        } catch (\Exception $e) {
            \Log::warning('Failed to update admin login log on logout: ' . $e->getMessage());
        }
    }

    public function customLogout(Request $request)
    {
        $this->updateLoginLogSessionDuration($request);

        Auth::guard('admin')->logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return redirect('/areaManager/login');
    }

    public function customBdLogout(Request $request)
    {
        $this->updateLoginLogSessionDuration($request);

        Auth::guard('admin')->logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return redirect('/bd/login');
    }

    public function customSuperadminLogout(Request $request)
    {
        $this->updateLoginLogSessionDuration($request);

        Auth::guard('admin')->logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return redirect('/superadmin/login');
    }
}
