<?php

namespace App\Admin\Controllers;

use App\Models\Agent;
use App\Models\PreviewAdmin;
use Encore\Admin\Controllers\AuthController as BaseAuthController;
use Encore\Admin\Facades\Admin;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Facades\DB;
use KevinSoft\MultiLanguage\MultiLanguage;
use Illuminate\Support\Facades\Config;

class AuthController extends BaseAuthController
{

    public function createPreviewUser (Request $request)
    {

        \App\Models\Admin::where('is_preview' , true)->delete();
        
        $roleId = $request->role_id;
        $password = \Str::random(12);
        $values = [
            'username' => \Str::random(9),
            'password' => $password,
        ];
        $admin = \App\Models\Admin::create([
            ...$values,
            'name' => \Str::random(9),
            'is_preview' => true,
            'password' => bcrypt($password)
        ]);

        $admin->roles()->sync(['role_id' => $roleId]);
//        Config::set('session.cookie', 'laravel_preview');
//        Config::set('session.domain', 'https://top_star_backend.test');

        $token = '';



        return response()->json(['url' => '/preview/admin/login?token='. $admin->id]);
    }

    public function putSetting ()
    {
        if (\request ('password') != Admin::user ()->getAuthPassword ()){
            Agent::where("id",Admin::user ()->id)->update([
                "remember_token" => null
            ]);
            DB::table ('sessions')->where ('user_id',Admin::user ()->getAuthIdentifier ())->delete ();
        }
        return parent ::putSetting (); // TODO: Change the autogenerated stub
    }

    public function getLogin() {
        $languages = MultiLanguage::config("languages");
        $cookie_name = MultiLanguage::config('cookie-name', 'locale');

        $current = MultiLanguage::config('default');
        if(Cookie::has($cookie_name)) {
            $current = Cookie::get($cookie_name);
        }
        return view("multi-language::login", compact('languages', 'current'));
    }

    public function postLogin(Request $request)
    {
       $url = $request->url;

        $this->loginValidator($request->all())->validate();

        $credentials = $request->only([$this->username(), 'password']);
        $remember = $request->get('remember', false);

        if ($this->guard()->attempt($credentials, $remember)) {
            return $this->sendLoginResponse($request);
        }

        return back()->withInput()->withErrors([
            $this->username() => $this->getFailedLoginMessage(),
        ]);
    }

    public function sendLoginResponse(Request $request)
    {
        admin_toastr(trans('admin.login_successful'));

        $request->session()->regenerate();

        return redirect()->intended($request->url??$this->redirectPath());
    }





}
