<?php

namespace App\Admin\Controllers;

use App\Helpers\Common;
use App\Http\Services\BannerServices;
use App\Models\Banner;
use Encore\Admin\Admin;
use Encore\Admin\Form;
use Encore\Admin\Grid;
use Encore\Admin\Layout\Content;
use Encore\Admin\Show;

class BannerController extends MainController
{
    /**
     * Title for current resource.
     *
     * @var string
     */


    public $permission_name = 'banners';

    public function index(Content $content)
    {
        $content
        ->title(trans('banners'))
        ->body($this->grid());
        return parent::index($content); // TODO: Change the autogenerated stub
    }

    /**
     * Show interface.
     *
     * @param mixed $id
     * @param Content $content
     * @return Content
     */
    public function show($id, Content $content)
    {
        return $content
            ->title(trans('banners'))
            ->body($this->detail($id));
    }

    /**
     * Edit interface.
     *
     * @param mixed $id
     * @param Content $content
     * @return Content
     */
    public function edit($id, Content $content)
    {
        return $content
            ->title(trans('banners'))
            ->body($this->form()->edit($id));
    }

   

    /**
     * Make a grid builder.
     *
     * @return Grid
     */
    protected function grid()
    {
        $grid = new Grid(new Banner());

        $grid->model()->orderByDesc('id');

        $grid->column('id', __('Id'));
        // $grid->column('title', __('Title'));
        // $grid->column('button_text', __('Button text'));
        $grid->column('image_url', __('Image url'))->image('', 100);
        // $grid->column('redirect_url', __('Redirect url'));
        $grid->column('publish_at', __('Publish at'));
        $grid->column('is_active', __('Is active'))->switch();
        $grid->column('updated_at', __('Updated at'));

        return $grid;
    }

    /**
     * Make a show builder.
     *
     * @param mixed $id
     * @return Show
     */
    protected function detail($id)
    {
        $show = new Show(Banner::findOrFail($id));

        $show->field('id', __('Id'));
        // $show->field('title', __('Title'));
        // $show->field('button_text', __('Button text'));
        $show->field('image_url', __('Image url'));
        // $show->field('redirect_url', __('Redirect url'));
        $show->field('publish_at', __('Publish at'));
        $show->field('is_active', __('Is active'));
        $show->field('expire', __('duration(days)'));
        $show->field('created_at', __('Created at'));
        $show->field('updated_at', __('Updated at'));

        return $show;
    }

    /**
     * Make a form builder.
     *
     * @return Form
     */
    protected function form()
    {

        $form = new Form(new Banner());

        // $form->text('title', __('Title'));
        // $form->text('button_text', __('Button text'));
        $form->image('image_url', __('Image url'))->required()->dir('banners')->disk('local');
        // $form->text('redirect_url', __('Redirect url'));
        $form->switch('publish_at', __('Publish Now'));
        $form->number('expire', __('duration(days)'));
        $form->switch('is_active', __('Is active'));
        return $form;
    }

    public function store()
    {
         $data = request()->all();
        (new BannerServices())->store($data);
    }

    public function update($id)
    {
        $data = request()->all();
//        dd($data);
        (new BannerServices())->update($id, $data);
    }

    public function create(Content $content)
    {
        $content
            ->title(trans('banners'))
            ->body($this->form());
        return parent::create($content); // TODO: Change the autogenerated stub
    }

    public function scripts(): array
    {
        return [
            // Include a JavaScript file to handle the conditional logic
            asset('js/nova-banner-form.js'),
        ];
    }
}
