<?php

namespace App\Admin\Controllers;

use App\Models\Banner;
use Encore\Admin\Form;
use Encore\Admin\Grid;
use Encore\Admin\Show;
use App\Helpers\Common;
use Encore\Admin\Admin;
use Encore\Admin\Layout\Content;
use App\Models\Admin as AdminModel;
use Illuminate\Support\Facades\Auth;

use App\Http\Services\BannerServices;
use App\Admin\Actions\DenyDeleteAction;

class BannerController extends MainController
{
    /**
     * Title for current resource.
     *
     * @var string
     */


    public $permission_name = 'banners';

    public function index(Content $content)
    {
        return parent::index($content
            ->title(trans('Splash'))
            ->body($this->grid()));
    }

    /**
     * Show interface.
     *
     * @param mixed $id
     * @param Content $content
     * @return Content
     */
    public function show($id, Content $content)
    {
        return $content
            ->title(trans('banners'))
            ->body($this->detail($id));
    }

    /**
     * Edit interface.
     *
     * @param mixed $id
     * @param Content $content
     * @return Content
     */
    public function edit($id, Content $content)
    {
        return $content
            ->title(trans('banners'))
            ->body($this->form()->edit($id));
    }

    public function update($id)
    {
        // $id = request()->route('id');
        $banner = Banner::find($id);
        $admin = Auth::user();
        $created = AdminModel::find($banner->created_by);
        if ((!$admin->isRole('developer')) && $created && ($created->isRole('developer'))) {
            admin_info(trans('messages.denyDelete'));
            return redirect()->route('admin.banners.index');
        } else {
            return $this->form()->update($id);
        }
    }



    /**
     * Make a grid builder.
     *
     * @return Grid
     */
    protected function grid()
    {
        $grid = new Grid(new Banner());

        $grid->model()->orderByDesc('id');

        $grid->column('id', __('Id'));
        // $grid->column('title', __('Title'));
        // $grid->column('button_text', __('Button text'));
        $grid->column('image_url', __('Image url'))->image('', 100);
        // $grid->column('redirect_url', __('Redirect url'));
        $grid->column('publish_at', __('Publish at'));
        $grid->column('is_active', __('Is active'))->switch();
        $grid->column('updated_at', __('Updated at'));

        $grid->actions(function ($actions) {
            $model = $actions->row;
            $admin = Auth::user();
            $created = AdminModel::find($model->created_by);

            // dd( $admin ,$created);
            if ((!$admin->isRole('developer')) && $created && ($created->isRole('developer'))) {
                $actions->disableDelete();
                $actions->add(new DenyDeleteAction());
            }
        });

        return $grid;
    }

    /**
     * Make a show builder.
     *
     * @param mixed $id
     * @return Show
     */
    protected function detail($id)
    {
        $show = new Show(Banner::findOrFail($id));

        $show->field('id', __('Id'));
        // $show->field('title', __('Title'));
        // $show->field('button_text', __('Button text'));
        $show->field('image_url', __('Image url'));
        // $show->field('redirect_url', __('Redirect url'));
        $show->field('publish_at', __('Publish at'));
        $show->field('is_active', __('Is active'));
        $show->field('expire', __('duration(days)'));
        $show->field('created_at', __('Created at'));
        $show->field('updated_at', __('Updated at'));

        return $show;
    }

    /**
     * Make a form builder.
     *
     * @return Form
     */
    protected function form()
    {

        $form = new Form(new Banner());

        $form->image('image_url', __('Image url'))->name(function ($file) {
            return now()->timestamp . rand(0, 999) . '.' . $file->guessExtension();
        });
        $form->switch('publish', __('Publish Now'));
        $form->number('expire', __('duration(days)'));
        $form->switch('is_active', __('Is active'));

        if ($form->isCreating()) {
            $form->model()->created_by = auth()->id();
        }
        $form->model()->updated_by = auth()->id();
        return $form;
    }

    //     public function store()
    //     {
    //          $data = request()->all();
    //         (new BannerServices())->store($data);
    //     }

    //     public function update($id)
    //     {
    //         $data = request()->all();
    // //        dd($data);
    //         (new BannerServices())->update($id, $data);
    //     }

    public function create(Content $content)
    {
        $content
            ->title(trans('banners'))
            ->body($this->form());
        return $content; // TODO: Change the autogenerated stub
    }

    public function scripts(): array
    {
        return [
            // Include a JavaScript file to handle the conditional logic
            asset('js/nova-banner-form.js'),
        ];
    }
}
