<?php

namespace App\Admin\Controllers;

use App\Admin\Actions\KickOfAgencyAction;
use App\Facades\ManagerHelper;
use App\Models\User;
use App\Models\Agency;
use Encore\Admin\Actions\Action;
use Encore\Admin\Form;
use Encore\Admin\Grid;
use Encore\Admin\Show;
use App\Helpers\Common;
use App\Models\AdminUser;
use Encore\Admin\Facades\Admin;
use Encore\Admin\Auth\Permission;

use Encore\Admin\Layout\Content;
use App\Admin\Actions\HostUserAction;
use Encore\Admin\Controllers\AdminController;
use Encore\Admin\Widgets\Table as WidgetsTable;
use Illuminate\Support\Facades\Hash;
use Encore\Admin\Actions\Response;

class EncorUsersController extends AdminController
{

    public $permission_name;
    public $hiddenColumns;

    protected $response;
    public function response()
    {
        if (is_null($this->response)) {
            $this->response = new Response();
        }

        if (method_exists($this, 'dialog')) {
            $this->response->swal();
        } else {
            $this->response->toastr();
        }

        return $this->response;
    }

    public function index ( Content $content )
    {
        if (!Admin::user()->can('*')){
            Permission::check('browse-'.$this->permission_name);
        }
        return parent ::index ( $content ); // TODO: Change the autogenerated stub
    }

    public function create ( Content $content )
    {
        if (!Admin::user()->can('*')){
            Permission::check('create-'.$this->permission_name);
        }

        return parent ::create ( $content ); // TODO: Change the autogenerated stub
    }

    public function update ( $id )
    {
        if (!Admin::user()->can('*')){
            Permission::check('update-'.$this->permission_name);
        }

        return parent ::update($id) ; // TODO: Change the autogenerated stub
    }

    public function show ( $id , Content $content )
    {
        if (!Admin::user()->can('*')){
            Permission::check('show-'.$this->permission_name);
        }

        return parent ::show ( $id , $content ); // TODO: Change the autogenerated stub
    }

    public function edit ( $id , Content $content )
    {
        if (!Admin::user()->can('*')){
            Permission::check('edit-'.$this->permission_name);
        }

        return parent ::edit ( $id , $content ); // TODO: Change the autogenerated stub
    }

    public function destroy ( $id )
    {
        if (!Admin::user()->can('*')){
            Permission::check('delete-'.$this->permission_name);
        }

        return parent::destroy ($id);
    }

    public function extendGrid($grid){
        $permission_name = $this->permission_name;

        if (!Admin::user()->can('*')) {
            if ( ! Admin ::user () -> can ( 'edit-' . $permission_name ) ) {
                $grid -> hiddenColumns = $this -> hiddenColumns;
            }
            if ( ! Admin ::user () -> can ( 'delete-' . $permission_name ) ) {
                $grid -> disableRowSelector ();
            }
            if ( ! Admin ::user () -> can ( 'create-' . $permission_name ) ) {
                $grid -> disableCreateButton ();
            }
            $grid -> actions (
                function ( $actions ) use ( $permission_name ) {

                    // The roles with this permission will not able to see the delete button in actions column.
                    if ( ! Admin ::user () -> can ( 'delete-' . $permission_name ) ) {
                        $actions -> disableDelete ();
                    }
                    if ( ! Admin ::user () -> can ( 'edit-' . $permission_name ) ) {
                        $actions -> disableEdit ();
                    }
                    if ( ! Admin ::user () -> can ( 'show-' . $permission_name ) ) {
                        $actions -> disableView ();
                    }

                }
            );
            if (! Admin ::user () -> can ( 'edit-' . $permission_name ) && ! Admin ::user () -> can ( 'delete-' . $permission_name ) && ! Admin ::user () -> can ( 'create-' . $permission_name )){
                $grid->disableActions ();
            }
        }



        $grid->export(function ($export) use ($grid){

            $export->filename($this->permission_name.'.csv');
          if($this->hiddenColumns == null)
          {
            $export->except([]);
          }else{
              $export->except($this->hiddenColumns);
          }

//            $export->only(['column3', 'column4' ...]);
//
            $export->originalValue($grid->columnNames);
//
//            $export->column('column_5', function ($value, $original) {
//                return $value;
//            });
        });

    }


    public function extendShow($show){
        if (!Admin::user()->can('*')) {
            $show -> panel ()
                -> tools (
                    function ( $tools ) {
                        $tools -> disableEdit ();
                        $tools -> disableList ();
                        $tools -> disableDelete ();
                    }
                );
        }
    }

    protected function title()
    {
        return trans('admin.administrator');
    }

    protected function grid()
    {
        $userModel = config('admin.database.users_model');

        $grid = new Grid(new $userModel());
        $grid->model()->where('is_preview', 0);
        $grid->column('id', 'ID')->sortable();
        $grid->column('username', trans('admin.username'));
        $grid->column('name', trans('admin.name'));
        $grid->column('roles', trans('admin.roles'))->pluck('name')->label();
        $grid->column('created_at', trans('admin.created_at'));
        $grid->column('updated_at', trans('admin.updated_at'));

        $grid->actions(function (Grid\Displayers\Actions $actions) {
            if ($actions->getKey() == 1) {
                $actions->disableDelete();
            }
        });

        $grid->tools(function (Grid\Tools $tools) {
            $tools->batch(function (Grid\Tools\BatchActions $actions) {
                $actions->disableDelete();
            });
        });

        return $grid;
    }

    /**
     * Make a show builder.
     *
     * @param mixed $id
     *
     * @return Show
     */
    protected function detail($id)
    {
        $userModel = config('admin.database.users_model');

        $show = new Show($userModel::findOrFail($id));

        $show->field('id', 'ID');
        $show->field('username', trans('admin.username'));
        $show->field('name', trans('admin.name'));
        $show->field('roles', trans('admin.roles'))->as(function ($roles) {
            return $roles->pluck('name');
        })->label();
        $show->field('permissions', trans('admin.permissions'))->as(function ($permission) {
            return $permission->pluck('name');
        })->label();
        $show->field('created_at', trans('admin.created_at'));
        $show->field('updated_at', trans('admin.updated_at'));

        return $show;
    }

    /**
     * Make a form builder.
     *
     * @return Form
     */
    public function form()
    {
        $userModel = config('admin.database.users_model');
        $permissionModel = config('admin.database.permissions_model');
        $roleModel = config('admin.database.roles_model');

        $form = new Form(new $userModel());

        $userTable = config('admin.database.users_table');
        $connection = config('admin.database.connection');

        $form->display('id', 'ID');
        $form->text('username', trans('admin.username'))
            ->creationRules(['required', "unique:{$connection}.{$userTable}"])
            ->updateRules(['required', "unique:{$connection}.{$userTable},username,{{id}}"]);

        $form->text('name', trans('admin.name'))->rules('required');
        $form->image('avatar', trans('admin.avatar'));
        $form->password('password', trans('admin.password'))->rules('required|confirmed');
        $form->password('password_confirmation', trans('admin.password_confirmation'))->rules('required')
            ->default(function ($form) {
                return $form->model()->password;
            });

        $form->ignore(['password_confirmation']);

        $form->multipleSelect('roles', trans('admin.roles'))->options($roleModel::all()->pluck('name', 'id'));
        $form->multipleSelect('permissions', trans('admin.permissions'))->options($permissionModel::all()->pluck('name', 'id'));

        $form->display('created_at', trans('admin.created_at'));
        $form->display('updated_at', trans('admin.updated_at'));

        $form->saving(function (Form $form) {
            if ($form->password && $form->model()->password != $form->password) {
                $form->password = Hash::make($form->password);
            }
        });

        return $form;
    }

}
