<?php

namespace App\Admin\Controllers;

use App\Admin\Actions\ChargeAction;
use App\Helpers\Common;
use App\Models\Agency;
use App\Models\Charge;
use App\Models\Country;
use App\Models\User;
use App\Traits\AdminTraits\AdminControllersTrait;
use Encore\Admin\Actions\Response;
use Encore\Admin\Auth\Permission;
use Encore\Admin\Controllers\AdminController;
use Encore\Admin\Facades\Admin;
use Encore\Admin\Form;
use Encore\Admin\Grid;
use Encore\Admin\Layout\Content;
use Encore\Admin\Show;
use Illuminate\Support\Facades\App;


class MainController extends AdminController
{


    public $permission_name;
    public $hiddenColumns;

    protected $response;
    public function response()
    {
        if (is_null($this->response)) {
            $this->response = new Response();
        }

        if (method_exists($this, 'dialog')) {
            $this->response->swal();
        } else {
            $this->response->toastr();
        }

        return $this->response;
    }

    public function index ( Content $content )
    {
        if (!Admin::user()->can('*')){
            Permission::check('browse-'.$this->permission_name);
        }
        return  $content; // TODO: Change the autogenerated stub
    }

    public function create ( Content $content )
    {
        if (!Admin::user()->can('*')){
            Permission::check('create-'.$this->permission_name);
        }
        return  $content ; // TODO: Change the autogenerated stub
    }

    public function update ( $id )
    {
        if (!Admin::user()->can('*')){
            Permission::check('edit-'.$this->permission_name);
        }

        return parent ::update($id) ; // TODO: Change the autogenerated stub
    }

    public function show ( $id , Content $content )
    {
        info($id);
        if (!Admin::user()->can('*')){
            Permission::check('show-'.$this->permission_name);
        }

        return  $content; // TODO: Change the autogenerated stub
    }

    public function edit ( $id , Content $content )
    {
        if (!Admin::user()->can('*')){
            Permission::check('edit-'.$this->permission_name);
        }

        return $content ; // TODO: Change the autogenerated stub
    }

    public function destroy ( $id )
    {
        if (!Admin::user()->can('*')){
            Permission::check('delete-'.$this->permission_name);
        }

        return parent::destroy ($id);
    }

    public function extendGrid($grid){
        $permission_name = $this->permission_name;

        if (!Admin::user()->can('*')) {
            if (!Admin::user()->can('edit-' . $permission_name) && !Admin::user()->can('update-' . $permission_name)) {
                $grid->hiddenColumns = is_array($this->hiddenColumns) ? $this->hiddenColumns : [];
            }
            if ( ! Admin ::user () -> can ( 'delete-' . $permission_name ) ) {
                $grid -> disableRowSelector ();
            }
            if ( ! Admin ::user () -> can ( 'create-' . $permission_name ) ) {
                $grid -> disableCreateButton ();
            }
            $grid -> actions (
                function ( $actions ) use ( $permission_name ) {

                    // The roles with this permission will not able to see the delete button in actions column.
                    if ( ! Admin ::user () -> can ( 'delete-' . $permission_name ) ) {
                        $actions -> disableDelete ();
                    }
                    if ( ! Admin ::user () -> can ( 'edit-' . $permission_name ) ) {
                        $actions -> disableEdit ();
                    }
                    if ( ! Admin ::user () -> can ( 'show-' . $permission_name ) ) {
                        $actions -> disableView ();
                    }

                }
            );
            if (! Admin ::user () -> can ( 'edit-' . $permission_name ) && ! Admin ::user () -> can ( 'delete-' . $permission_name ) && ! Admin ::user () -> can ( 'create-' . $permission_name )){
                $grid->disableActions ();
            }
        }



        $grid->export(function ($export) use ($grid){

            $export->filename($this->permission_name.'.csv');
          if($this->hiddenColumns == null)
          {
            $export->except([]);
          }else{
              $export->except($this->hiddenColumns);
          }

//            $export->only(['column3', 'column4' ...]);
//
            $export->originalValue($grid->columnNames);
//
//            $export->column('column_5', function ($value, $original) {
//                return $value;
//            });
        });

    }


    public function extendShow($show){
        if (!Admin::user()->can('*')) {
            $show -> panel ()
                -> tools (
                    function ( $tools ) {
                        $tools -> disableEdit ();
                        $tools -> disableList ();
                        $tools -> disableDelete ();
                    }
                );
        }
    }



}
