<?php

namespace App\Http\Resources\Api\V1;

use App\Helpers\Common;
use App\Http\Resources\CountryResource;
use App\Models\Follow;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Resources\Json\JsonResource;

class UserRelationsResource extends JsonResource
{
    public static $vipsReceivedImages = null;
    public static $vipsSenderImages = null;
    public static $userFollowers = null;

    public function __construct($resource) {  parent::__construct($resource); }

    /**
     * Transform the resource into an array.
     *
     * @param \Illuminate\Http\Request $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {

        $pass_status = false;

        $now_room = $this->room;

        if ($now_room) {
            if ($now_room->room_pass != null && $now_room->room_pass != '') {
                $pass_status = true;
            }
        }

        if(self::$userFollowers != null && count(self::$userFollowers) > 0){
            $isFollow = in_array($this->id, self::$userFollowers);
        }else{
            $isFollow = @(bool)Common::IsFollow(@$request->user()->id, $this->id);

        }

        if (!self::$vipsReceivedImages && !self::$vipsSenderImages) {
            $imageReceiver = $this->getImageReceiverOrSender('receiver_id', 1);
            $imageSender   = $this->getImageReceiverOrSender('sender_id', 2);
        } else {
            $imageReceiver = count(self::$vipsReceivedImages) > 0 ? self::$vipsReceivedImages->where('level', $this->total_received_level)->first() : null;
            $imageSender = count(self::$vipsSenderImages) > 0 ? self::$vipsSenderImages->where('level', $this->total_sender_level)->first() : null;
        }
        $frameAbility = $this->followPacks->where('type', 4)->first();
        $user = User::where('id', $this->id)->first();
        $data         = [
            'id'             => @$this->id,
            'uuid'           => @$this->uuid,
            'name'           => @$this->name ?: '',
            'followers' => @$user->follower,
            'following' => @$user->following,
            'friends' => @$user->friend,
            'id_image'             => @$this->specialId?->ware?->show_img ?? '',
            'special_id'          =>  @$this->specialId?->ware?->id ?? 0,
            'profile'        => [
                'image'  => @$this->profile->avatar,
                'age'    => Carbon::parse(@$this->profile->birthday)->age,
                'gender' => @$this->profile->gender ?? 1,
                'country'=> @$this->profile->country?:'',
            ],
            'country'=> new CountryResource($this->resource),
            'frame'          => $frameAbility ? (@$this->ware->img2 ?: @$this->ware->img1) : '',
            'frame_id'       => @$this->dress_1,
            'now_room'             =>  new NowRoomResource($this)
                        // [
            //     'is_in_room'      => @$this->now_room_uid != 0,
            //     'uid'             => @$this->now_room_uid,
            //     'is_mine'         => @$this->id == $this->now_room_uid,
            //     'password_status' => $pass_status
            // ]
            ,
            'vip'            => [
                'level' => @$this->UserVip->level,
            ],
            'level'          => [
                'receiver_img' => $imageReceiver ? @$imageReceiver->img : '',
                'sender_img'   => $imageSender ? @$imageSender->img : '',
                'sender_level'  =>@$this->total_sender_level ?? 0,
                'reciver_level' =>@$this->total_received_level ?? 0
            ],
            'online_time'    => $this->online_time ? date("Y-m-d H:i:s", $this->online_time) : '',
            'has_color_name' => count($this->followPacks->where('type', 18)) > 0,
            'is_followed'            => Follow::where(['followed_user_id' => $request->user()->id ,"user_id" => $this->id])->first() != null ? true : false,
            'is_follow'      => $isFollow,
            "is_gold_id" => (bool)$this->is_gold_id,
            'type_user'            => intval(@$this->type_user) ?: 0, // both
            "manger_type"          =>new MangerTypeResource(@$this->manager),
            "multi_images"          => $this->images?->select("img"),
            "statistic"     => [
                "visitors" => count($this->profileVisits),
                "licked" => count($this->likes),
                "followers" => count($this->followers),
                "bio" => $this->bio,
            ],
            'image_color'          => @$this->color_image,
        ];

        return $data;
    }

    public function additional(array $data)
    {
        return parent::additional($data); // T-18 Change the autogenerated stub
    }

    /**
     * @return array
     */
    public function getAdditional(): array
    {

        return $this->additional;
    }

    /**
     * @param array $additional
     */
    public function setAdditional(array $additional): void
    {

        $this->additional = $additional;
    }

    public static function initializeData($vipsReceivedImages, $vipsSenderImages, $userFollowers)
    {
        self::$vipsSenderImages = $vipsSenderImages;
        self::$vipsReceivedImages = $vipsReceivedImages;
        self::$userFollowers = $userFollowers;
    }

    public static function clear()
    {
        self::$vipsSenderImages = null;
        self::$vipsReceivedImages = null;
        self::$userFollowers = null;


    }


}
