name: SSh-bigo-room-pipline
on:
  push:
    branches: ["bigo-room"]
jobs:
  run_bigo-room_hub:
    runs-on: [self-hosted] #ubuntu-latest
    steps:
    - name: print out bigo-room
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: "34.18.164.14"
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.UTDVM }}
        port: ${{ secrets.PORT }}
        command_timeout: 5m
        script: |
          cd /var/www/bigo-room
          source /home/${{ secrets.USERNAME }}/scripts/hub.sh
          threshold=80
          current=$(df -h | awk '$NF=="/"{printf "%d", $5}' | sed 's/%//')
          if [ $current -gt $threshold ]; then
            echo "Disk space is more than $threshold% utilized"
          # Execute the command to clean up Docker system
            docker system prune -a -f && docker system prune --all --force && echo "Docker system cleaned successfully"
          else
            echo "Disk space is within acceptable limits $current% "
          fi
  run_bigo-room_app:
    runs-on: [self-hosted] #ubuntu-latest
    needs: run_bigo-room_hub
    steps:
    - name: print out bigo-room
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: "34.18.164.14"
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.UTDVM }}
        port: ${{ secrets.PORT }}
        command_timeout: 20m
        script: |
          cd /var/www/bigo-room
          pwd
          #source /home/${{ secrets.USERNAME }}/scripts/hub.sh
          docker build -t bigo-room:${{ github.sha }} .
          docker service update --image bigo-room:${{ github.sha }} bigo-room-app

          # Get container ID of task 5live-app.1
          CONTAINER_ID=$(docker ps --filter "name=bigo-room-app.1" --format "{{.ID}}" | head -n 1)

          # Run artisan command inside that container
          if [ -n "$CONTAINER_ID" ]; then
            docker exec  $CONTAINER_ID php artisan whatsapp:change-token
          else
            echo "No running container found for bigo-room-app.1 service task"
            exit 1
          fi

          # check again
          threshold=80
          current=$(df -h | awk '$NF=="/"{printf "%d", $5}' | sed 's/%//')
          if [ $current -gt $threshold ]; then
            echo "Disk space is more than $threshold% utilized"
          # Execute the command to clean up Docker system
            docker system prune -a -f && docker system prune --all --force && echo "Docker system cleaned successfully"
          else
            echo "Disk space is within acceptable limits $current% "
          fi
  run_bigo-room_job:
    runs-on: [self-hosted] #ubuntu-latest
    needs: run_bigo-room_hub
    steps:
    - name: print out bigo-room Job
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: "34.18.164.14"
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.UTDVM }}
        port: ${{ secrets.PORT }}
        command_timeout: 20m
        script: |
          cd /var/www/bigo-room
          pwd
          #source /home/${{ secrets.USERNAME }}/scripts/hub.sh
          docker build -t bigo-room-job:${{ github.sha }} -f Dockerfile-jobs .
          docker service update --image bigo-room-job:${{ github.sha }} bigo-room-job
