name: SSh-developers-pipline
on:
  push:
    branches: ["new-developer"]
jobs:
  run_developers_job:
    runs-on: [self-hosted]
    steps:
    - name: print out developers test
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: "34.18.18.32"
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.UTDVM }}
        port: ${{ secrets.PORT }}
        command_timeout: 5m
        script: |
          cd /var/www/for-developer
          source /home/${{ secrets.USERNAME }}/scripts/hub.sh
          php artisan migrate --force
          php artisan optimize:clear
