name: SSh-tempo-pipline
on:
  push:
    branches: ["tempoApp"]
jobs:
  run_example_job:
    runs-on: ubuntu-latest
    steps:
    - name: print out Tempo
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: "34.18.56.160"
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.UTDVM }}
        port: ${{ secrets.PORT }}
        script: |
          echo "$USER"
          cd /var/www/tempo
          pwd
          source /home/${{ secrets.USERNAME }}/scripts/hub.sh
          php artisan migrate --force
          php artisan optimize:clear
          docker build -t tempo:${{ github.sha }} .
          docker service update --image tempo:${{ github.sha }} tempo-app
