name: SSh-tempo-pipline
on:
  push:
    branches: ["tempoApp"]
jobs:
  run_example_job:
    runs-on: ubuntu-latest
    steps:
    - name: print out Tempo
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: "34.18.53.132"
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.UTDVM }}
        port: ${{ secrets.PORT }}
        command_timeout: 3m
        first_ssh: |
          echo "$USER"
          pwd
          cd /var/www/tempo
          pwd
          source /home/${{ secrets.USERNAME }}/scripts/hub.sh
          php artisan migrate --force
          php artisan optimize:clear
          docker build -t tempo:${{ github.sha }} .
          docker service update --image tempo:${{ github.sha }} tempo-app
