name: SSh-tempo-pipline
on:
  push:
    branches: ["tempoApp"]
jobs:
  run_example_job:
    runs-on: ubuntu-latest
    steps:
    - name: print out Tempo
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: "34.18.56.160"
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.UTDVM }}
        port: ${{ secrets.PORT }}
        script: |
          threshold=75
          current=$(df -h | awk '$NF=="/"{printf "%d", $5}' | sed 's/%//')
          if [ $current -gt $threshold ]; then
            echo "Disk space is more than $threshold% utilized"
          # Execute the command to clean up Docker system
            docker system prune -a -f && docker system prune --all --force && echo "Docker system cleaned successfully"
          else
            echo "Disk space is within acceptable limits"
          fi
          cd /var/www/tempo
          pwd
          source /home/${{ secrets.USERNAME }}/scripts/hub.sh
          docker build -t tempo:${{ github.sha }} .
          docker service update --image tempo:${{ github.sha }} tempo-app
          # check again
          threshold=75
          current=$(df -h | awk '$NF=="/"{printf "%d", $5}' | sed 's/%//')
          if [ $current -gt $threshold ]; then
            echo "Disk space is more than $threshold% utilized"
          # Execute the command to clean up Docker system
            docker system prune -a -f && docker system prune --all --force && echo "Docker system cleaned successfully"
          else
            echo "Disk space is within acceptable limits"
          fi
