name: SSh-test-pipline
on:
  push:
    branches: ["test"]
jobs:
  run_example_job:
    runs-on: ubuntu-latest
    steps:
    - name: print out tempo-feature test
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: "34.18.53.132"
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.UTDVM }}
        port: ${{ secrets.PORT }}
        command_timeout: 3m
        script: |
          echo "$USER"
          cd /var/www/tempo
          pwd
          source /home/${{ secrets.USERNAME }}/scripts/hub.sh
          php artisan migrate
          php artisan optimize:clear
