name: SSh-zeno-chat-pipline
on:
  push:
    branches: ["zeno-chat"]
jobs:
  run_zeno_chat_hub:
    runs-on: [self-hosted]
    steps:
    - name: pull latest code
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: "34.18.211.121"
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.UTDVM }}
        port: ${{ secrets.PORT }}
        command_timeout: 3m
        script: |
          cd /var/www/zeno-chat
          source /home/${{ secrets.USERNAME }}/hub.sh
          threshold=80
          current=$(df -h | awk '$NF=="/"{printf "%d", $5}' | sed 's/%//')
          if [ $current -gt $threshold ]; then
            echo "Disk space is more than $threshold% utilized"
            docker system prune -a -f && docker system prune --all --force && echo "Docker system cleaned successfully"
          else
            echo "Disk space is within acceptable limits $current% "
          fi
  run_zeno_chat_app:
    runs-on: [self-hosted]
    needs: run_zeno_chat_hub
    steps:
    - name: build and deploy zeno-chat app
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: "34.18.211.121"
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.UTDVM }}
        port: ${{ secrets.PORT }}
        command_timeout: 20m
        script: |
          cd /var/www/zeno-chat
          pwd
          docker build -t zeno-chat-octa:${{ github.sha }} -f Dockerfile-octana .
          docker service update --image zeno-chat-octa:${{ github.sha }} zeno-chat-octa
          threshold=80
          current=$(df -h | awk '$NF=="/"{printf "%d", $5}' | sed 's/%//')
          if [ $current -gt $threshold ]; then
            echo "Disk space is more than $threshold% utilized"
            docker system prune -a -f && docker system prune --all --force && echo "Docker system cleaned successfully"
          else
            echo "Disk space is within acceptable limits $current% "
          fi
  run_zeno_chat_job:
    runs-on: [self-hosted]
    needs: run_zeno_chat_hub
    steps:
    - name: build and deploy zeno-chat job
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: "34.18.211.121"
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.UTDVM }}
        port: ${{ secrets.PORT }}
        command_timeout: 20m
        script: |
          cd /var/www/zeno-chat
          pwd
          docker build -t zeno-chat-job:${{ github.sha }} -f Dockerfile-jobs .
          docker service update --image zeno-chat-job:${{ github.sha }} zeno-chat-job
